[package]
name = "simple-server"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["steveklabnik <steve@steveklabnik.com>", "ashleygwilliams <ashley666ashley@gmail.com>"]

[dependencies]
scoped_threadpool = "0.1.7"
httparse = "1.2.3"
http = "0.1.0"
